[package]
name = "termblog-web"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bytes.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3"
termblog-core = { path = "../core" }
termblog-proto = { path = "../proto" }
axum = { version = "0.8", features = ["ws"] }
futures = "0.3"
tower-http = { version = "0.6", features = ["fs"] }
