[package]
name = "termblog-web"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bytes.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3"
termblog-core = { path = "../core" }
termblog-config = { path = "../../config" }
termblog-proto = { path = "../proto" }
axum = { version = "0.8", features = ["ws"] }
futures = "0.3"
serde.workspace = true
serde_json.workspace = true
termblog-commentd = { path = "../commentd" }
termblog-statd = { path = "../statd" }
termblog-content-model = { path = "../../content-model" }
tower-http = { version = "0.6", features = ["fs"] }

[dev-dependencies]
tempfile = "3"
